### ISSUE TITLE
Cannot compile chemicals: Na2HPO4 and KH2PO4.

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#28]
After making a list of chemical objects, I am trying to compile them. 
```python
chemical_list = ('Na2HPO4', 'KH2PO4')
chemical_objects = tmo.Chemicals([])
    for chemical in chemical_list:
        try:
            chemical_objects.append(tmo.Chemical(chemical))
        except LookupError:
            chemical_objects.append(create_fake_chemical(chemical))

chemical_objects.compile()
```

However, Na2HPO4 and KH2PO4 show the next error:
```python
Traceback (most recent call last):
  File "/Users/dim/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4df983869c2e>", line 1, in <module>
    runfile('/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/initial.py', wdir='/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/initial.py", line 77, in <module>
    chemicals.compile()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/_chemicals.py", line 159, in compile
    CompiledChemicals._compile(self)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/_chemicals.py", line 304, in _compile
    f"{chemical} is missing key thermodynamic properties ({missing}); "
RuntimeError: Na2HPO4 is missing key thermodynamic properties (Psat, Tb and Hvap); use the `<Chemical>.get_missing_properties()` to check all missing properties
```
The same I get for KH2PO4. 
chemical.default() doesn't help

## Environment
Python: anaconda, 3.7
OS: macOS Catalina version 10.15.2
BioSTEAM: v 2.19.15
biorefineries v 2.14.15

**Comment by yalinli2** [comment]
As suggested by the error, Na2HPO4 is missing Psat, Tb, and Hvap (so does KH2PO4), those properties won't be added by the default function, so you need to define these values before compiling.

The following should work:
```python
import thermosteam as tmo

chemical_list = ('Na2HPO4', 'KH2PO4')
chemical_objects = tmo.Chemicals([])

for chemical in chemical_list:
    try:
        chemical_objects.append(tmo.Chemical(chemical))
    except LookupError:
        chemical_objects.append(create_fake_chemical(chemical))

chemical_objects.Na2HPO4.Psat.add_model(0) # set Psat to a constant
chemical_objects.Na2HPO4.Hvap.add_model(0) # set Hvap to a constant
chemical_objects.Na2HPO4.Tb = 1000

chemical_objects.KH2PO4.Psat.add_model(0) # set Psat to a constant
chemical_objects.KH2PO4.Hvap.add_model(0) # set Hvap to a constant
chemical_objects.KH2PO4.Tb = 1000

chemical_objects.compile()

chemical_objects.Na2HPO4.show()
chemical_objects.KH2PO4.show()
```
Note that I was using filler values for those properties, Psat and Hvap, you can copy Psat and Hvap models from other chemicals, e.g.:
```python
Water = tmo.Chemical('Water')
chemical_objects.Na2HPO4.copy_models_from(Water, ['Hvap', 'Psat'])
hemical_objects.Na2HPO4.Psat # you can check the models
Water.Psat(373)
chemical_objects.Na2HPO4.Psat(373) # the same as water
```

**Comment by yoelcortes** [comment]
Hi Dmitry, great to hear from you. For solids or dissolved solids, we can give them a phase and BioSTEAM won't ask you for Psat, Hvap and Tb. 

```python
Na2HPO4 = tmo.Chemical('Na2HPO4', phase='s', default=True)
KH2PO4 = tmo.Chemical('KH2PO4', phase='s', default=True)
chemicals = tmo.Chemicals([Na2HPO4, KH2PO4])
chemicals.compile()
```
Yalin's example works, but it a chemical only exists in one phase in the process, best to specify it.

Let me know if you have anymore questions!

**Comment by DmitryBachin** [comment]
Thank you very much. 
Under the mentioned code both solutions worked just fine. 

Then I have added the stream with the salts as a part of an in-stream to the Fermentation object.

Then the solution of @yalinli2 worked just fine.

The solutions of @yoelcortes caused this error:
```python
Traceback (most recent call last):
  File "/Users/dim/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0368ba7aaa53>", line 1, in <module>
    runfile('/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/cut_out_fermentation.py', wdir='/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/cut_out_fermentation.py", line 20, in <module>
    sys.simulate()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/biosteam/_system.py", line 653, in simulate
    self._converge()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/biosteam/_system.py", line 586, in _converge
    return self._converge_method() if self._recycle else self._run()
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/biosteam/_system.py", line 561, in _run
    run_unit_in_path(i)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/biosteam/_system.py", line 57, in run_unit_in_path
    try_method_with_object_stamp(unit, method)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/exceptions.py", line 71, in try_method_with_object_stamp
    raise_error_with_object_stamp(object, error)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/exceptions.py", line 63, in raise_error_with_object_stamp
    raise error
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/exceptions.py", line 67, in try_method_with_object_stamp
    return method(*args)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/biosteam/units/_fermentation.py", line 237, in _run
    effluent.mix_from(self.ins)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/_stream.py", line 757, in mix_from
    H = sum([i.H for i in others])
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/_stream.py", line 757, in <listcomp>
    H = sum([i.H for i in others])
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/_stream.py", line 590, in H
    return self.mixture.H(self.phase, self.mol, *self._thermal_condition)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/mixture/mixture.py", line 122, in H
    H = self._H(phase, mol, T)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/base/phase_handle.py", line 114, in __call__
    return getattr(self, phase)(z, T, P)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/mixture/ideal_mixture_model.py", line 56, in __call__
    return sum([j * i(T, P) for i, j in zip(self.models, mol) if j])
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/mixture/ideal_mixture_model.py", line 56, in <listcomp>
    return sum([j * i(T, P) for i, j in zip(self.models, mol) if j])
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/base/functor.py", line 195, in __call__
    return self.function(T, **self.__dict__)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/properties/free_energy.py", line 35, in Solid_Enthalpy_Ref_Liquid
    return H_ref - H_int_Tm_to_T_ref_l - Hfus + Cn_s.integrate_by_T(Tm, T)
TypeError: <Fermentation: R301> unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by yoelcortes** [comment]
You were probably missing the heat of fusion (Hfus) and melting temperature (Tm) since we assumed its a solid. Since the chemical will always be in the given state, these values wouldn't actually make a difference in the energy balance (enthalpy is a state function). I just updated thermosteam so that this would work without having to pass Hfus and Tm:

```python
import thermosteam as tmo
Na2HPO4 = tmo.Chemical('Na2HPO4', phase='s', default=True)
KH2PO4 = tmo.Chemical('KH2PO4', phase='s', default=True)
chemicals = tmo.Chemicals([Na2HPO4, KH2PO4])

# Test
tmo.settings.set_thermo(chemicals)
stream = tmo.Stream(None, Na2HPO4=1, KH2PO4=1, T=310)
stream.H # -> 2348.7323046048014
```

**Comment by yoelcortes** [comment]
I'd still suggest to pass the phase to chemical. It will prevent bugs in separations later
