### ISSUE TITLE
Problems with outflow after running the simulation

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#31]
I have to in-streams to the mixer. One contains water and solid stuff, other contains "solid" bacteria. 

After running the simulation, I am trying to show F_vol of the out-stream. It causes crash.

If I run the media with only liquid compounds (another stream "bacteria_stream" contains only "solid" bacteria), then I have no problems. 

## The code:
```python
import thermosteam as tmo
import biosteam as bst


def create_fake_chemical(chem_id):
    """
    made mostly for bacteria and biomass
    :param chem_id:
    :return:
    """
    chemical = tmo.Chemical.blank(chem_id, MW=1., phase='s')
    chemical.default()
    return chemical


def introducing_chemicals(chemical_list):
    """
    creating chemical objects related to compounds which are a part of bio process
    :param chemical_list:
    :return:
    """
    solid_chemicals_with_problems = ('Na2HPO4', 'KH2PO4', "CaCl2")
    chemical_objects = tmo.Chemicals([])
    for chemical in chemical_list:
        if chemical in solid_chemicals_with_problems:
            chemical_objects.append(tmo.Chemical(chemical, phase='s', default=True))
            continue
        try:
            chemical_objects.append(tmo.Chemical(chemical))
        except LookupError:
            chemical_objects.append(create_fake_chemical(chemical))
    return chemical_objects


media = {
    'CaCl2': 0.0111,
    'Glucose': 20.0,
    'MgSO4': 0.012,
    'NH4Cl': 1.0,
    'NaCl': 0.5,
    'Water': 1000,
    'thiamine': 6e-06,
    # 'Na2HPO4': 7.0,
    # "KH2PO4": 3.0
}
other_chemicals = ("Vanillin", "O2", "CO2", "Ecoli")
chemicals = introducing_chemicals([*other_chemicals, *[c for c, _ in media.items()]])

bst.settings.set_thermo(chemicals)

media_stream = bst.Stream('media', T=295, units='kg/hr', **media)
bacteria_stream = bst.Stream('Bacteria', T=295, units='kg/hr', Water=1000)
media_mix = bst.units.Mixer('Mixer')
[media_stream, bacteria_stream] - media_mix
s1 = media_mix.outs[0]
media_mix.simulate()
print(s1.F_vol)

```

## The output:
```python
Traceback (most recent call last):
  File "/Users/dim/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ef0394a537f0>", line 1, in <module>
    runfile('/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/upstream.py', wdir='/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dim/PycharmProjects/bioprocess_modelling/Bellossom/upstream.py", line 57, in <module>
    print(s1.F_vol)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/_stream.py", line 580, in F_vol
    return 1000. * self.mixture.V(self.phase, self.mol, *self._thermal_condition)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/base/phase_handle.py", line 114, in __call__
    return getattr(self, phase)(z, T, P)
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/mixture/ideal_mixture_model.py", line 56, in __call__
    return sum([j * i(T, P) for i, j in zip(self.models, mol) if j])
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/mixture/ideal_mixture_model.py", line 56, in <listcomp>
    return sum([j * i(T, P) for i, j in zip(self.models, mol) if j])
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/base/thermo_model_handle.py", line 370, in __call__
    Tmin=self.Tmin, Tmax=self.Tmax,
  File "/Users/dim/opt/anaconda3/lib/python3.7/site-packages/thermosteam/base/thermo_model_handle.py", line 275, in Tmin
    return min([i.Tmin for i in self._models])
ValueError: min() arg is an empty sequence
```
## Environment
Python: anaconda, 3.7
OS: macOS Catalina version 10.15.2
BioSTEAM: v 2.19.15
biorefineries v 2.14.15

## Addition
I have the same output if I try to run media_stream.F_vol in the same code even before simulation.

**Comment by DmitryBachin** [comment]
Addition:
I have the same output if I try to run media_stream.F_vol in the same code even before simulation.

**Comment by yoelcortes** [comment]
Seems like the following chemicals are missing the liquid phase molar volume model:

```python
>>> for chemical in chemicals:
>>>    V = chemical.V
>>>    V = V.l if hasattr(V, 'l') else V
>>>    if not V.models: print(chemical)
Glucose
MgSO4
thiamine
```

Even though you where able compile these chemicals, they only have molar volume models for either solid or ideal gas. I would suggest you set the state, then default properties (before you compile the chemicals):

```python
for i in chemicals['Glucose', 'MgSO4', 'thiamine']:
    i.at_state('s')
    i.default()
```

I tried this out and it worked. I attached here the test file, [Dmitry_test.txt](https://github.com/BioSTEAMDevelopmentGroup/biosteam/files/4827028/Dmitry_test.txt). Let me know if you have anymore questions!

**Comment by yoelcortes** [comment]
I also made an update to thermosteam so that you can get better errors when no models are available (thanks for posting the issue!).

You should get the following error when you retry the code you provided:
```python
DomainError: Glucose (CAS: 492-61-5) has no valid liquid molar volume model at T=295.00 K and P=101325 Pa
```

**Comment by DmitryBachin** [comment]
Yes. Now it works! Thank you very much!
