### ISSUE TITLE
The split function has disappeared after one of the updates

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#52]
**Describe the bug**
I didn't update biosteam for a while, but now I have downloaded the last version. For one of my units I used the split function which was also used in other virtual equipment.

**To Reproduce**
```python
from biosteam.units.design_tools.separations import split
```
**Expected behavior**
just usage of the split function

**Actual behavior**
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ad53f2ea018f>", line 1, in <module>
    runfile('/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/tea.py', wdir='/Users/dmitrybachin/PycharmProjects/bioprocess_modelling')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/tea.py", line 9, in <module>
    from general.garage import UniversalFermenter
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/general/garage.py", line 8, in <module>
    from biosteam.units.design_tools.separations import split
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'biosteam.units.design_tools.separations'
```

**Version**
 - Python 3.8
 - biosteam 2.22.7
 - macOS Catalina 10.15.6

**Comment by yoelcortes** [comment]
Good to hear from you again, Dmitry. The [separations](https://thermosteam.readthedocs.io/en/latest/separations.html#thermosteam.separations.split) module (along with the split function) has been moved to thermosteam since version [2.20](https://biosteam.readthedocs.io/en/latest/updates/2.20.html#id3). 

I appreciate the code to reproduce the error and detailed traceback!
Let me know if you run into anything else,

**Comment by DmitryBachin** [comment]
Thank you very much!
