### ISSUE TITLE
Pressure filter gives error if split is specified

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#60]
**Describe the bug**
In the case of a custom split, the class initiation gives an error.

**To Reproduce**
 ```python
F301 = bst.PressureFilter("F301",
                              outs=('cake', 'protein_solution'),
                              split=split_solid,
                              moisture_content=0.3
                              )
```

**Expected behavior**
Successful initiation of the class object. 

**Actual behavior**
 ```python
Traceback (most recent call last):
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5f148d2e0836>", line 1, in <module>
    runfile('/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Spinarak/fermentation.py', wdir='/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Spinarak')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Spinarak/fermentation.py", line 142, in <module>
    fs = generate_fermentation_system(0.42, input_info)
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Spinarak/fermentation.py", line 118, in generate_fermentation_system
    F301 = bst.PressureFilter("F301",
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/biosteam/units/solids_separation.py", line 365, in __init__
    remove_undefined_chemicals(split, chemicals)
UnboundLocalError: local variable 'chemicals' referenced before assignment
```

**Version**
 - biosteam 2.29

**Additional context**

the __init__ requests variable chemicals, which is created only if split is not specified (None). 
solution: just move the line chemicals = self.chemicals before the if statement

**Comment by yalinli2** [comment]
Thanks Dmitry! I think Yoel has already fixed this as you suggested in 208394d, I'll close this issue.
