### ISSUE TITLE
Solid Heat capacity method (RuntimeError)

### ISSUE THREAD

**Issue by internEVbiotech** [BioSTEAMDevelopmentGroup/biosteam#65]
Since the last update in BioSteam, apparently, an error is blocking the performance of a code developed by my supervisor Dimitry. Inside the module, receive_vent is used to retrieve effluent streams. Currently a RuntimeError: <UniversalFermenter: F201> solid heat capacity method 'USER_METHOD' computed an invalid value of 117359.64292799997 J/mol/K for component with CASRN 'SpiderSilk' is printed at the terminal. (SpiderSilk is a trademark  protein product with a high molecular weight)

The following code is used to retrieve vent information:

        for compound_id, amount in self.borrow.items():
            if effluent.imol[compound_id] < amount:
                print(f"[WARNING]{compound_id} is not sufficient, the fermenter should be reprogrammed")
                effluent.imol[compound_id] = 0
            else:
                effluent.imol[compound_id] -= amount
        vent.receive_vent(effluent,accumulate=True)

It is expected that no error should stop the performance of the code.

![Expected part causing the error](https://user-images.githubusercontent.com/79700800/133099728-142bb7b4-9df8-4314-9578-5cd2b8207bb0.png)

**Version**
 - Python 3.9

**Additional context**
Could the error be traced to the new changes in the thermodynamic library? If so, what is the remedy for solving this issue? Choosing a different solver method did not make much of a difference. 

The complete error output is given here:

C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\biosteam\units\solids_separation.py:119: RuntimeWarning: cannot define water split, only moisture content
  SolidsSeparator.__init__(self, ID, ins, outs, thermo, moisture_content=moisture_content, split=split, order=order)
C:\EvBiotech_intern\bioprocess_modelling\Spinarak\general\garage.py:660: RuntimeWarning: cannot define water split, only moisture content
  bst.SolidsSeparator.__init__(self, unit_id, ins, outs,
C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\equilibrium\fugacities.py:50: RuntimeWarning: H2SO4 has no defined Dortmund groups; functional group interactions are ignored
  self.gamma = thermo.Gamma(chemicals)
[WARNING]Ammonium_sulfate is not sufficient, the fermenter should be reprogrammed
Traceback (most recent call last):
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\_stream.py", line 1122, in mix_from
    self.H = H
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\_multi_stream.py", line 402, in H
    self.T = self.mixture.xsolve_T(self._imol, H, *self._thermal_condition)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\mixture.py", line 336, in xsolve_T
    args = (H, self.xH, phase_mol, P, self.xCn(phase_mol, T_guess))
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\mixture.py", line 341, in xCn
    return sum([self.Cn(phase, mol, T) for phase, mol in phase_mol])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\mixture.py", line 341, in <listcomp>
    return sum([self.Cn(phase, mol, T) for phase, mol in phase_mol])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\base\phase_handle.py", line 84, in __call__
    return getattr(self, phase)(z, T, P)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\ideal_mixture_model.py", line 102, in __call__
    return sum([j * i(T) for i, j in zip(self.models, mol) if j])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\ideal_mixture_model.py", line 102, in <listcomp>
    return sum([j * i(T) for i, j in zip(self.models, mol) if j])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermo\utils\t_dependent_property.py", line 1939, in T_dependent_property
    raise RuntimeError("%s method '%s' computed an invalid value of %s %s for component with CASRN '%s'" %(self.name, method, prop, self.units, self.CASRN))
RuntimeError: solid heat capacity method 'USER_METHOD' computed an invalid value of 117359.64292799997 J/mol/K for component with CASRN 'SpiderSilk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EvBiotech_intern\bioprocess_modelling\Spinarak\fermentation.py", line 191, in <module>
    fs = generate_fermentation_system(0.42, input_info)
  File "C:\EvBiotech_intern\bioprocess_modelling\Spinarak\fermentation.py", line 177, in generate_fermentation_system
    fermentation_system.simulate()
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\biosteam\_system.py", line 1162, in simulate
    self._converge()
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\biosteam\_system.py", line 1082, in _converge
    self._run()
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\biosteam\_system.py", line 1048, in _run
    if isa(i, Unit): run(i, i.run)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\exceptions.py", line 76, in try_method_with_object_stamp
    raise_error_with_object_stamp(object, error)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\exceptions.py", line 68, in raise_error_with_object_stamp
    raise error
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\exceptions.py", line 72, in try_method_with_object_stamp
    return method(*args)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\biosteam\_unit.py", line 650, in run
    self._run()
  File "C:\EvBiotech_intern\bioprocess_modelling\Spinarak\general\garage.py", line 306, in _run
    vent.receive_vent(effluent,accumulate=True)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\_stream.py", line 1894, in receive_vent
    ms.mix_from([self, other])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\_stream.py", line 1127, in mix_from
    self.H = H
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\_multi_stream.py", line 402, in H
    self.T = self.mixture.xsolve_T(self._imol, H, *self._thermal_condition)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\mixture.py", line 336, in xsolve_T
    args = (H, self.xH, phase_mol, P, self.xCn(phase_mol, T_guess))
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\mixture.py", line 341, in xCn
    return sum([self.Cn(phase, mol, T) for phase, mol in phase_mol])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\mixture.py", line 341, in <listcomp>
    return sum([self.Cn(phase, mol, T) for phase, mol in phase_mol])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\base\phase_handle.py", line 84, in __call__
    return getattr(self, phase)(z, T, P)
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\ideal_mixture_model.py", line 102, in __call__
    return sum([j * i(T) for i, j in zip(self.models, mol) if j])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermosteam\mixture\ideal_mixture_model.py", line 102, in <listcomp>
    return sum([j * i(T) for i, j in zip(self.models, mol) if j])
  File "C:\Users\alinz\AppData\Local\Programs\Python\Python39\lib\site-packages\thermo\utils\t_dependent_property.py", line 1939, in T_dependent_property
    raise RuntimeError("%s method '%s' computed an invalid value of %s %s for component with CASRN '%s'" %(self.name, method, prop, self.units, self.CASRN))
RuntimeError: <UniversalFermenter: F201> solid heat capacity method 'USER_METHOD' computed an invalid value of 117359.64292799997 J/mol/K for component with CASRN 'SpiderSilk'

Process finished with exit code 1

**Comment by yoelcortes** [comment]
Hi! Thanks for submitting the issue. This has to do with some checks thermo performs before spitting out the answer. Thermo thinks that 117359.64292799997 J/mol/K is too high (but it is correct for your case). You can increase the maximum value of heat capacity with the following lines:

```
from thermo import HeatCapacity
HeatCapacity.property_max  = 1e12
```

You can read up more on thermo here, but always feel free to post the issue first:
https://thermo.readthedocs.io/

Thanks!
