### ISSUE TITLE
The distillation simulation problem

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#72]
**Describe the bug**
The distillation simulation doesn't work because of light key composition is infeaseable.

**To Reproduce**
``` python
import biosteam as bst

solvent_id = "Ethyl acetate"
target_product = "Limonene"
bst.settings.set_thermo(["Limonene", "Ethyl acetate"])

chems = {"Limonene": 0.035968827016585624,
         "Ethyl acetate": 11.3500781793385}

instream = bst.Stream("innnn", **chems)

bottom_key = 1e-2
D301 = bst.BinaryDistillation("D301", LHK=(solvent_id, target_product),
                              k=1.05, y_top=1 - bottom_key, x_bot=bottom_key,
                              outs=("", "product"))

instream - D301

D301.simulate()

``` 

**Expected behavior**
The solvent should be evaporated while the product stay liquid

**Actual behavior**
```python
Traceback (most recent call last):
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-91f384b791ce>", line 1, in <module>
    runfile('/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Gloom_g/playground.py', wdir='/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Gloom_g')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/Gloom_g/playground.py", line 19, in <module>
    D301.simulate()
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/biosteam/_unit.py", line 810, in simulate
    self.run()
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/biosteam/_unit.py", line 724, in run
    self._run()
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/biosteam/units/distillation.py", line 1112, in _run
    self._run_binary_distillation_mass_balance()
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/biosteam/units/distillation.py", line 565, in _run_binary_distillation_mass_balance
    self._check_mass_balance()
  File "/Users/dmitrybachin/PycharmProjects/bioprocess_modelling/venv/lib/python3.8/site-packages/biosteam/units/distillation.py", line 509, in _check_mass_balance
    raise InfeasibleRegion("light key composition")
thermosteam.exceptions.InfeasibleRegion: light key composition is infeasible
``` 
**Version**
- Python 3.8
- biosteam 2.31.4
- macOS Big Sur 11.5.2

**Comment by DmitryBachin** [comment]
Thank you very much!
